language: csharp
dotnet: 3.1.201
mono: none
matrix:
  include:
    - os: linux
      dist: bionic
      before_install:
        #- sudo apt remove nodejs && sudo apt autoremove
        #- curl -sL https://deb.nodesource.com/setup_13.x | sudo -E bash -
        - nvm use 11
        - sudo apt-get -qq update && sudo apt-get install -y graphviz
        - node --version
        - npm --version
    - os: osx
      addons:
        homebrew:
          update: true
          packages:
            - node
            - graphviz
script:
  - export PATH="$PATH:$HOME/.dotnet/tools"
  - dotnet tool install -g Cake.Tool --version 0.37.0
  - dotnet cake build.cake
  - dotnet cake build.cake --target=Run-Unit-Tests
# disable for now while RazorLight is in pre-release
#  - dotnet cake build.cake --target=Publish-Artifacts