language: csharp
dotnet: 3.1.201
mono: none
matrix:
  include:
    - os: linux
      dist: bionic
      before_install:
        - sudo apt remove nodejs && sudo apt autoremove
        - curl -sL https://deb.nodesource.com/setup_13.x | sudo -E bash -
        - sudo apt-get install -y nodejs
    - os: osx
      addons:
        homebrew:
          packages:
            - node
script:
  - export PATH="$PATH:$HOME/.dotnet/tools"
  - dotnet tool install -g Cake.Tool --version 0.37.0
  - dotnet cake build.cake
  - dotnet cake build.cake --target=Run-Unit-Tests
  - dotnet cake build.cake --target=Publish-Artifacts