version: 1.0.{build}
image: Visual Studio 2019

install:
  - cmd: dotnet --info
  - cmd: node --version
  - ps: Install-Product node $env:nodejs_version

# build platform, i.e. x86, x64, Any CPU. This setting is optional.
platform: Any CPU

# build Configuration, i.e. Debug, Release, etc.
configuration: Release

environment:
  nodejs_version: "Current"
  MYSQL_PWD: Password12!
  MYSQL_PATH: C:\Program Files\MySql\MySQL Server 5.7
  PGUSER: postgres
  PGPASSWORD: Password12!
  POSTGRES_PATH: C:\Program Files\PostgreSQL\12

init:
  - SET PATH=%POSTGRES_PATH%\bin;%MYSQL_PATH%\bin;%PATH%
  - ps: >-
      Get-ChildItem -Path 'HKLM:\SOFTWARE\Microsoft\Microsoft SQL Server\' |
      Where-Object {
          $_.Name -imatch 'MSSQL[_\d]+\.SQL.*';
      } |
      ForEach-Object {
          Write-Host "Setting $((Get-ItemProperty $_.PSPath).'(default)') to dynamic ports";
          Set-ItemProperty (Join-Path $_.PSPath 'mssqlserver\supersocketnetlib\tcp\ipall') -Name TcpDynamicPorts -Value '0';
          Set-ItemProperty (Join-Path $_.PSPath 'mssqlserver\supersocketnetlib\tcp\ipall') -Name TcpPort -Value ([string]::Empty);
      }

services:
  - mssql2017
  - postgresql12
  - mysql

build_script:
  - mysql -e "create database schematic;" --user=root
  - createdb schematic
  - ps: ./build.ps1

test_script:
  - ps: ./build.ps1 -Target Run-Unit-Tests

after_test:
  - ps: ./build.ps1 -Target Publish-Artifacts

notifications:
- provider: Email
  to:
    - '{{commitAuthorEmail}}'
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: true
