version: 1.0.{build}
image: Visual Studio 2017

install:
  - cmd: dotnet --info

# build platform, i.e. x86, x64, Any CPU. This setting is optional.
platform: Any CPU

# build Configuration, i.e. Debug, Release, etc.
configuration: Release

environment:
  MYSQL_PWD: Password12!
  MYSQL_PATH: C:\Program Files\MySql\MySQL Server 5.7
  PGUSER: postgres
  PGPASSWORD: Password12!
  POSTGRES_PATH: C:\Program Files\PostgreSQL\9.6

init:
  - SET PATH=%POSTGRES_PATH%\bin;%MYSQL_PATH%\bin;%PATH%

services:
  - mssql2016
  - postgresql96
  - mysql

build_script:
  - mysql -e "create database schematic;" --user=root
  - createdb schematic
  - ps: ./build.ps1

notifications:
- provider: Email
  to:
    - '{{commitAuthorEmail}}'
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: true
