version: 1.0.{build}
image: Visual Studio 2017

install:
  - cmd: dotnet --info
  - cmd: dotnet restore src

# build platform, i.e. x86, x64, Any CPU. This setting is optional.
platform: Any CPU

# build Configuration, i.e. Debug, Release, etc.
configuration: Release

environment:
  MYSQL_PWD: Password12!
  MYSQL_PATH: C:\Program Files\MySql\MySQL Server 5.7
  PGUSER: postgres
  PGPASSWORD: Password12!
  POSTGRES_PATH: C:\Program Files\PostgreSQL\9.6

init:
  - SET PATH=%POSTGRES_PATH%\bin;%MYSQL_PATH%\bin;%PATH%

services:
  - mssql2016
  - postgresql96
  - mysql

build:
  verbosity: minimal

test_script:
  - dotnet test src/SJP.Schematic.Core.Tests/SJP.Schematic.Core.Tests.csproj --configuration Release --logger:trx;LogFileName=SJP.Schematic.Core.Tests.results.xml
  - ps: build/uploadtests.ps1 "src/SJP.Schematic.Core.Tests/TestResults/SJP.Schematic.Core.Tests.results.xml"
  - dotnet test src/SJP.Schematic.Modelled.Tests/SJP.Schematic.Modelled.Tests.csproj --configuration Release --logger:trx;LogFileName=SJP.Schematic.Modelled.Tests.results.xml
  - ps: build/uploadtests.ps1 "src/SJP.Schematic.Modelled.Tests/TestResults/SJP.Schematic.Modelled.Tests.results.xml"
  - dotnet test src/SJP.Schematic.Modelled.Reflection.Tests/SJP.Schematic.Modelled.Reflection.Tests.csproj --configuration Release --logger:trx;LogFileName=SJP.Schematic.Modelled.Reflection.Tests.results.xml
  - ps: build/uploadtests.ps1 "src/SJP.Schematic.Modelled.Reflection.Tests/TestResults/SJP.Schematic.Modelled.Reflection.Tests.results.xml"
  - dotnet test src/SJP.Schematic.Sqlite.Tests/SJP.Schematic.Sqlite.Tests.csproj --configuration Release --logger:trx;LogFileName=SJP.Schematic.Sqlite.Tests.results.xml
  - ps: build/uploadtests.ps1 "src/SJP.Schematic.Sqlite.Tests/TestResults/SJP.Schematic.Sqlite.Tests.results.xml"
  - dotnet test src/SJP.Schematic.SqlServer.Tests/SJP.Schematic.SqlServer.Tests.csproj --configuration Release --logger:trx;LogFileName=SJP.Schematic.SqlServer.Tests.results.xml
  - ps: build/uploadtests.ps1 "src/SJP.Schematic.SqlServer.Tests/TestResults/SJP.Schematic.SqlServer.Tests.results.xml"
  - mysql -e "create database schematic;" --user=root
  - dotnet test src/SJP.Schematic.MySql.Tests/SJP.Schematic.MySql.Tests.csproj --configuration Release --logger:trx;LogFileName=SJP.Schematic.MySql.Tests.results.xml
  - ps: build/uploadtests.ps1 "src/SJP.Schematic.MySql.Tests/TestResults/SJP.Schematic.MySql.Tests.results.xml"
  - createdb schematic
  - dotnet test src/SJP.Schematic.PostgreSql.Tests/SJP.Schematic.PostgreSql.Tests.csproj --configuration Release --logger:trx;LogFileName=SJP.Schematic.PostgreSql.Tests.results.xml
  - ps: build/uploadtests.ps1 "src/SJP.Schematic.PostgreSql.Tests/TestResults/SJP.Schematic.PostgreSql.Tests.results.xml"
  - dotnet test src/SJP.Schematic.DataAccess.Tests/SJP.Schematic.DataAccess.Tests.csproj --configuration Release --logger:trx;LogFileName=SJP.Schematic.DataAccess.Tests.results.xml
  - ps: build/uploadtests.ps1 "src/SJP.Schematic.DataAccess.Tests/TestResults/SJP.Schematic.DataAccess.Tests.results.xml"
  - dotnet test src/SJP.Schematic.DataAccess.EntityFrameworkCore.Tests/SJP.Schematic.DataAccess.EntityFrameworkCore.Tests.csproj --configuration Release --logger:trx;LogFileName=SJP.Schematic.DataAccess.EntityFrameworkCore.Tests.results.xml
  - ps: build/uploadtests.ps1 "src/SJP.Schematic.DataAccess.EntityFrameworkCore.Tests/TestResults/SJP.Schematic.DataAccess.EntityFrameworkCore.Tests.results.xml"
  - dotnet test src/SJP.Schematic.DataAccess.OrmLite.Tests/SJP.Schematic.DataAccess.OrmLite.Tests.csproj --configuration Release --logger:trx;LogFileName=SJP.Schematic.DataAccess.OrmLite.Tests.results.xml
  - ps: build/uploadtests.ps1 "src/SJP.Schematic.DataAccess.OrmLite.Tests/TestResults/SJP.Schematic.DataAccess.OrmLite.Tests.results.xml"
  - dotnet test src/SJP.Schematic.DataAccess.Poco.Tests/SJP.Schematic.DataAccess.Poco.Tests.csproj --configuration Release --logger:trx;LogFileName=SJP.Schematic.DataAccess.Poco.Tests.results.xml
  - ps: build/uploadtests.ps1 "src/SJP.Schematic.DataAccess.Poco.Tests/TestResults/SJP.Schematic.DataAccess.Poco.Tests.results.xml"
  - dotnet test src/SJP.Schematic.Lint.Tests/SJP.Schematic.Lint.Tests.csproj --configuration Release --logger:trx;LogFileName=SJP.Schematic.Lint.Tests.results.xml
  - ps: build/uploadtests.ps1 "src/SJP.Schematic.Lint.Tests/TestResults/SJP.Schematic.Lint.Tests.results.xml"

notifications:
- provider: Email
  to:
    - simon@sjp.co.nz
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: true
